### ISSUE TITLE
Relaxing fobi causes INVALID ELEMENT ERROR

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-obo#120]
### Describe the bug

Running `robot relax` as preprocessing on [fobi](http://www.obofoundry.org/ontology/fobi.html) fails with the following:
```
15:28:40  ROBOT preprocessing: relax fobi
15:28:40  Relaxing /tmp/fobifbzig241 to /tmp/tmpjiynjm76_fobi_relaxed.owl...
15:28:40  ROBOT encountered an error: 
15:28:40  
15:28:40    RAN: /var/lib/jenkins/workspace/knowledge-graph-hub_kg-obo_main/gitrepo/robot relax --input /tmp/fobifbzig241 --output /tmp/tmpjiynjm76_fobi_relaxed.owl --vvv
15:28:40  
15:28:40    STDOUT:
15:28:40  2021-10-26 19:28:37,761 DEBUG org.obolibrary.robot.IOHelper - Loading ontology /tmp/fobifbzig241 with catalog file null
15:28:40  2021-10-26 19:28:37,764 DEBUG org.semanticweb.owlapi.utilities.Injector - Loading file META-INF/services/org.semanticweb.owlapi.model.OWLOntologyManager
15:28:40  2021-10-26 19:28:37,764 DEBUG org.semanticweb.owlapi.utilities.Injector - Loading URL for service jar:file:/var/lib/jenkins/workspace/knowledge-graph-hub_kg-obo_main/gitrepo/robot.jar!/META-INF/services/org.semanticweb.owlapi.model.OWLOntologyManager
15:28:40  2021-10-26 19:28:37,764 DEBUG org.semanticweb.owlapi.utilities.Injector - Loading URL for service jar:file:/var/lib/jenkins/workspace/knowledge-graph-hub_kg-obo_main/gitrepo/robot.jar!/META-INF/services/org.semanticweb.owlapi.... (12839 more, please see e.stdout)
15:28:40  
15:28:40    STDERR:
15:28:40  java.io.IOException: errors#INVALID ELEMENT ERROR "http://purl.obolibrary.org/obo/fobi.owl#FOBI:050339" contains invalid characters
15:28:40  	at org.obolibrary.robot.IOHelper.saveOntologyFile(IOHelper.java:1724)
15:28:40  	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:838)
15:28:40  	at org.obolibrary.robot.CommandLineHelper.maybeSaveOutput(CommandLineHelper.java:671)
15:28:40  	at org.obolibrary.robot.RelaxCommand.execute(RelaxCommand.java:113)
15:28:40  	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:248)
15:28:40  	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:192)
15:28:40  	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
15:28:40  	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:60)
15:28:40  ERROR:kg-obo:ROBOT relaxing of fobi failed - skipping.
```

### To Reproduce

```
python3 run.py --s3_test --bucket kg-test --get_only fobi
```

## Expected behavior

This bug is caught and only causes the transform of fobi to fail.
I believe this transform still doesn't work even if fobi is not relaxed first, but there may be as simple as trimming the #FOBI:050339 part from the IRI.

### Version

6071b55c205a4c7dcc2e89aca35f1cbbc9ec002a

**Comment by caufieldjh** [comment]
Note that FOBI completely fails in the OBO Dashboard too: http://dashboard.obofoundry.org/dashboard/index.html

**Comment by caufieldjh** [comment]
Closing as this is an issue with `fobi` and not with `kg-obo`.
