### ISSUE TITLE
Problem transforming chebi

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-obo#40]
### Describe the bug

[Runtime error](https://build.berkeleybop.io/job/knowledge-graph-hub/job/kg-obo/job/main/22/) when pushing chebi transform:

```
11:29:49  INFO:kg-obo:chebi_nodes.tsv 102144331 bytes
11:29:49  INFO:kg-obo:chebi_edges.tsv 64121999 bytes
11:29:49  INFO:kg-obo:Successfully completed transform of chebi
11:29:49  
processing ontologies:   1%|          | 1/193 [50:43<162:20:28, 3043.90s/it]
11:29:49  Traceback (most recent call last):
11:29:49    File "run.py", line 39, in <module>
11:29:49      run()
11:29:49    File "/var/lib/jenkins/workspace/knowledge-graph-hub_kg-obo_main/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
11:29:49      return self.main(*args, **kwargs)
11:29:49    File "/var/lib/jenkins/workspace/knowledge-graph-hub_kg-obo_main/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1062, in main
11:29:49      rv = self.invoke(ctx)
11:29:49    File "/var/lib/jenkins/workspace/knowledge-graph-hub_kg-obo_main/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
11:29:49      return ctx.invoke(self.callback, **ctx.params)
11:29:49    File "/var/lib/jenkins/workspace/knowledge-graph-hub_kg-obo_main/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 763, in invoke
11:29:49      return __callback(*args, **kwargs)
11:29:49    File "run.py", line 36, in run
11:29:49      run_transform(skip, get_only, bucket, save_local, s3_test)
11:29:49    File "/var/lib/jenkins/workspace/knowledge-graph-hub_kg-obo_main/gitrepo/kg_obo/transform.py", line 349, in run_transform
11:29:49      track_obo_version(ontology_name, owl_iri, owl_version, bucket)
11:29:49    File "/var/lib/jenkins/workspace/knowledge-graph-hub_kg-obo_main/gitrepo/kg_obo/transform.py", line 160, in track_obo_version
11:29:49      client.upload_file(track_file_local_path, bucket)
11:29:49  TypeError: upload_file() missing 1 required positional argument: 'Key'
```

### To Reproduce

See [here](https://build.berkeleybop.io/job/knowledge-graph-hub/job/kg-obo/job/main/22/)

## Expected behavior

Should transform

### Version

https://github.com/Knowledge-Graph-Hub/kg-obo/commit/8554da26757fc5b04ffbc519b10cbfff20c4db48

**Comment by caufieldjh** [comment]
See #42
